TrailAir.Web.UI/Controllers/ExperimentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TrailAir.DB;
using TrailAir.DB.Models.Base;
using TrailAir.UI.Modelling.Managers;
using TrailAir.Web.UI.Controllers.Base;

namespace TrailAir.Web.UI.Controllers
{
    public class ExperimentController : BaseWebController
    {
        public ExperimentController(TrailAirDbContext context, ApplicationUserManager userManager, IConfiguration configuration, SignInManager<ApplicationUser> signInManager)
            : base(context, userManager, configuration, signInManager)
        {
        }

        public IActionResult List()
        {
            return View();
        }

        // Unnecessary complex routing example in .Net
        [Route("{lang}/[controller]/[action]/{experimentId}/{participantId}")]
        public IActionResult ExperimentWizardCalibrate(int experimentId, string participantId)
        {
            ViewBag.experimentId = experimentId;
            ViewBag.participantId = participantId;

            return View("ExperimentWizardSteps/ExperimentWizardCalibrate");
        }
        
        [Route("{lang}/[controller]/[action]/{experimentId}/{participantId}")]
        public IActionResult ExperimentWizardSamplePicker(int experimentId, string participantId)
        {
            ViewBag.experimentId = experimentId;
            ViewBag.participantId = participantId;

            return View("ExperimentWizardSteps/ExperimentWizardSamplePicker");
        }
        
        [Route("{lang}/[controller]/[action]/{experimentId}/{participantId}/{expTestSamplId}/{baseExperimentResultType}")]
        public IActionResult ExperimentWizardTest(int experimentId, string participantId, int expTestSamplId, int expControlSamplId)
        {
            ViewBag.experimentId = experimentId;
            ViewBag.participantId = participantId;
            ViewBag.expTestSamplId = expTestSamplId;
           // ViewBag.baseExperimentResultType = baseExperimentResultType; DEPRECATED We are not using anymore benchmarks 

            return View("ExperimentWizardSteps/ExperimentWizardTest");
        }

        [Route("{lang}/[controller]/[action]/{experimentId}/{participantId}")]
        public IActionResult ExperimentWizardResume(int experimentId, string participantId, int experimentResultId)
        {
            ViewBag.experimentId = experimentId;
            ViewBag.participantId = participantId;
            ViewBag.experimentResultId = experimentResultId;

            return View("ExperimentWizardSteps/ExperimentWizardResume");
        }
    }
}

TrailAir.Web.UI/Views/Experiment/ExperimentWizardSteps/ExperimentWizardCalibrate.cshtml
<div class="row wrapper purple-2-bg page-heading flex-column align-items-center">
     <br />
    <div class="col-lg-12">
        <h2 class="purple-title">
            @*TODO: Replace this with static text*@
            Calibrate Control Sample: {{ currentElement.sampleCode }}
        </h2>
    </div>
    <br />
        @*-------  START: Start timer --------*@
    <div class="col-lg-12 d-flex justify-content-center" style="min-height: 37.5px;">
        <button v-show="!timerStarted" type="button" class="btn btn-info btn-lg" v-on:click="startTimer()"
                style="border-radius:18px; max-width: 190px; width:100%;">
            <div class="d-flex justify-content-around" style="max-height: 20px;">
                <p style="margin:unset;">Start timer </p>
                <i style="margin-top: 2px;" class="fa fa-clock-o"></i>
            </div>
        </button> @*TODO: Replace this with static text*@
        <div v-show="timerStarted" class="h-100" style="display: flex;">
            <h2 style="margin:unset" class="purple-title" id="minutes">00</h2>
            <h2 style="margin:unset">:</h2>
            <h2 style="margin:unset" class="purple-title" id="seconds">00</h2>
        </div>
    </div>
    <br /><br />
    <div class="col-lg-8 d-flex justify-content-center" style="min-height: 37.5px;">

        @*-------  START: Fragrance detected --------*@
        <div class="col-lg-4 d-flex justify-content-end h-100">
            <button :class="!timerStarted || timerStopped ? 'btn btn-lg btn-secondary':'btn btn-info btn-lg'" v-show="!firstDetectionTimeSet" :disabled="!timerStarted || timerStopped" type="button" v-on:click="onFragranceDetected()"
                    style="border-radius:18px; max-width: 190px; width:100%;">
                <div class="d-flex justify-content-around" style="max-height: 20px;">
                    <p style="margin:unset;">Fragrance detected </p>
                    <i style="margin-top: 2px;" class="fa fa-clock-o"></i>
                </div>
            </button> @*TODO: Replace this with static text*@
            <div v-show="firstDetectionTimeSet" style="display:flex; justify-content: end;">
                <div class="col-lg-12 d-flex h-100 align-items-center">
                    <div class="d-flex w-100 justify-content-between align-items-center">
                        <p style="margin:2px">{{firstDetTimeFormatted}}</p>
                        <p style="margin:5px">Fragrance detected</p>
                        <i class="fa fa-check-circle" style="font-size:25px; color: green;"></i>
                    </div>
                </div>
            </div>
        </div>
        @*-------  END: Fragrance detected --------*@

        @*-------  START: Build up --------*@
        <div class="col-lg-4 d-flex justify-content-center h-100">
            <button :class="!firstDetectionTimeSet || (firstDetectionTimeSet && timerStopped) ? 'btn btn-lg btn-secondary':'btn btn-info btn-lg'" v-show="!buildUpTimeSet" :disabled="!firstDetectionTimeSet || (firstDetectionTimeSet && timerStopped)" type="button" v-on:click="onBuildup()"
                    style="border-radius:18px; max-width: 190px; width:100%;">
                <div class="d-flex justify-content-around" style="max-height: 20px;">
                    <p style="margin:unset;">Build up </p>
                    <i style="margin-top: 2px;" class="fa fa-clock-o"></i>
                </div>
            </button> @*TODO: Replace this with static text*@
            <div v-show="buildUpTimeSet" style="display:flex; justify-content: center;">
                <div class="col-lg-12 d-flex h-100 align-items-center">
                    <div class="d-flex w-100 justify-content-between align-items-center">
                        <p style="margin:2px">{{buildUpTimeFormatted}}</p>
                        <p style="margin:5px">Build up</p>
                        <i class="fa fa-check-circle" style="font-size:25px; color: green;"></i>
                    </div>
                </div>
            </div>
        </div>
        @*-------  END: Build up --------*@

        @*-------  START: Full fragrance --------*@
        <div class="col-lg-4 d-flex justify-content-start h-100">
            <button :class="!firstDetectionTimeSet ? 'btn btn-lg btn-secondary':'btn btn-info btn-lg'" v-show="!fullDetTimeSet" :disabled="!firstDetectionTimeSet" type="button" v-on:click="onFullFragrance()"
                    style="border-radius:18px; max-width: 190px; width:100%;">
                <div class="d-flex justify-content-around" style="max-height: 20px;">
                    <p style="margin:unset;">Full fragrance</p>
                    <i style="margin-top: 2px;" class="fa fa-clock-o"></i>
                </div>
            </button> @*TODO: Replace this with static text*@
            <div v-show="fullDetTimeSet" style="display:flex; justify-content: start;">
                <div class="col-lg-12 d-flex h-100 align-items-center">
                    <div class="d-flex w-100 justify-content-between align-items-center">
                        <p style="margin:2px">{{fullDetTimeFormatted}}</p>
                        <p style="margin:5px">Full fragrance</p>
                        <i class="fa fa-check-circle" style="font-size:25px; color: green;"></i>
                    </div>
                </div>
            </div>
        </div>
        @*-------  END: Full fragrance --------*@
    </div>
    <br /><br /><br /><br />
    @*-------  END: Start timer --------*@

    @*-------  START: Intensity--------*@
    <div class="col-lg-12">
        <div class="col-lg-8 m-auto d-flex flex-column align-items-center">
            <h4 class="purple-title">Please rate the perceived intensity</h4>@*TODO: Replace this with static text*@
            <div class="col-lg-12">
                <div id="Intensity_Slider" class="round-custom-slider"></div>
            </div>
        </div>
    </div>
    <br /><br /><br /><br /><br /><br />
    @*-------  END: Intensity --------*@


    <div class="col-lg-12 d-flex">
        @*-------  START: Attributes --------*@
        <div class="col-lg-6 d-flex flex-column align-items-center">
            <h4 class="purple-title">Choose up to 5 attributes to describe the character of the sample.</h4> @*TODO: Replace this with static text*@
            <br />
            <div class="col-lg-10">
                <div class="d-flex mb-2" v-for="(att, index) in currentElement.attributeTexts">
                    <h4 class=" col-lg-1">{{index + 1}}</h4>
                    <input type="text" class="form-control col-lg-10" v-model="currentElement.attributeTexts[index]" value="">
                </div>
            </div>
        </div>
        @*-------  END: Attributes --------*@


        @*-------  START: Sensation --------*@
        <div class="col-lg-6 d-flex flex-column align-items-center">
            <h4 class="purple-title">Additional Comments</h4> @*TODO: Replace this with static text*@
            <br />
            <div class="col-lg-10">
                @*TODO: Replace this with static text*@
                <textarea type="text" class="form-control" style="height: 216px;" v-model="currentElement.sensation" placeholder="Write your notes ...">
                </textarea>
            </div>
        </div>
        @*-------  END: Sensation --------*@
    </div>
    <br /><br />

@*
    <div class="d-flex align-items-center flex-column" style="max-width: 600px; background-color: white; width: 100%;">
        <br />
        <br />
        <img src="~/images/CalibrateLogoPurple-TransparentBack.PNG" />
        <br />
        <h3 class="purple-title">
           
            Insert control sample:
        </h3>
        <br />
        <br />
        <h4 style="text-align: center;">Control Sample</h4>  
        <h3 style="text-align: center;">{{currentElement.controlSample.controlSampleTypeName}}</h3>
        <br />
        <h4 style="text-align: center;">Intensity score</h4>
        <h3 style="text-align: center;">{{currentElement.controlSample.controlSampleTypeIntensityScore}}</h3>
        <br />
        <h4 style="text-align: center;">New intensity score</h4>
        <div class="col-lg-12">
            <div id="calibrateIntensitySlider" class="round-custom-slider"></div>
        </div>
        <br />
        <br />
    </div>*@

    @*-------  START: Next sample button --------*@
    <div class="col-lg-12 d-flex">
        <div class="col-lg-6">
            <div class="col-lg-6 d-flex justify-content-start pl-0">
                <button type="button" class="btn btn-danger btn-lg" v-on:click="dontSave()"
                        style="border-radius:18px; max-width: 190px; width:100%;">
                    <div class="d-flex justify-content-center" style="max-height: 20px;">
                        <p style="margin:unset;">Don't save </p>
                    </div>
                </button> @*TODO: Replace this with static text*@
            </div>
        </div>
        <div class="col-lg-6 d-flex justify-content-center">
            <div class="col-lg-8 d-flex justify-content-end">

                <button type="button" class="btn btn-success btn-lg" v-on:click="saveAndOpenExpSamplePicker()"
                        style="border-radius:18px; max-width: 190px; width:100%;">
                    <div class="d-flex justify-content-between" style="max-height: 20px;">
                        <p style="margin:unset;">Continue</p>
                        <i style="margin-top: 2px;" class="fa fa-arrow-right"></i>
                    </div>
                </button> @*TODO: Replace this with static text*@
            </div>
        </div>
    </div>
    @*-------  END: Next sample button --------*@
</div>
<br />
<br />
<br />

@section Scripts{
    <script type="text/javascript">
        var experimentIdGlobal = @ViewBag.experimentId;
        var participantIdGlobal = "@ViewBag.participantId";
        var experimentWizardSamplePickerPage = "@Url.Action("ExperimentWizardSamplePicker", "Experiment")";
        var experimentListPage = "@Url.Action("List","Experiment")";
    </script>
    <link href="~/lib/nouslider/latest/nouislider.css" rel="stylesheet">

        @*----  Main JS file for this Component ----*@
    <script src="~/lib/nouslider/latest/nouislider.min.js" asp-append-version="true"></script>
    <script src="~/js/Models/Experiment.js" asp-append-version="true"></script>
    <script src="~/js/ExperimentWizardSteps/ExperimentWizardCalibrate.js" asp-append-version="true"></script>

}

TrailAir.Web.UI/Views/Experiment/ExperimentWizardSteps/ExperimentWizardResume.cshtml
<div class="row wrapper page-heading align-items-center flex-column">

    <single-exp-result ref="singleExpResult"></single-exp-result>

    <div class="col-lg-12 d-flex justify-content-center">
        <h2 class="purple-title">
            Resume
        </h2>
    </div>@*TODO: Replace this with static text*@
    <br /><br />
    <div class="col-lg-10 wizard-vert-table-size">
        <table class="table table-stripped table-hover no-margins toggle-arrow-tiny resume-table">
            <thead>
                <tr class="no-border-table-headers">
                    <th class=" wizard-table-samp-max-width"></th>
                    <th class="purple-title wizard-table-int-max-width" style="text-align: center;">
                        <div class="col-lg-12">
                            Intensity
                        </div>
                    </th>
                    <th class="purple-title wizard-table-desc-width vertical-purple-dots-left" style="text-align: center;">
                        <div class="col-lg-12">
                            Descriptors
                        </div>
                    </th>
                    <th class="purple-title  vertical-purple-dots-left" style="text-align: start;">
                        <div class="col-lg-12">
                            Sensation
                        </div>
                    </th>
                    <th class="wizard-table-mod-max-width"></th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="exResult in experimentResultsList">
                    <td class="purple-title wizard-table-samp-max-width">
                        <h3 class="m-0">{{ exResult.expResultType==3? "Control Sample: " + exResult.computedName : "Sample S"+exResult.sampleIndex }}</h3>
                    </td>
                    <td class="wizard-table-int-max-width">
                        <div class="d-flex justify-content-end">
                            <div class="d-flex align-items-end">
                                <h1 class="purple-title m-0" style="padding: 0 0 10px 0;">
                                    {{ exResult.intensity }}
                                </h1>
                                <h1 class="" style="margin: 0 5px 0 0">/10</h1>
                            </div>
                        </div>
                    </td>
                    <td class="wizard-table-desc-width vertical-purple-dots-left">
                        <table class="wizard-desc-column-tbl">
                            <tr v-for="(attr, index) in exResult.attributeTexts">
                                <td>{{ index + 1 }} </td>
                                <td>{{ attr == "" ? "-" : attr }}</td>
                            </tr>
                        </table>
                    </td>
                    <td class=" vertical-purple-dots-left">
                        <div class="col-lg-12">
                            {{ exResult.sensation }}
                        </div>
                    </td>
                    <td class="wizard-table-mod-max-width">
                        <div class="d-flex h-100  cursor-pointer" v-on:click="modify(exResult.id, exResult.expResultType);">
                            <i style="font-size:22px; margin-right:10px;" class="fa fa-pencil purple-title"></i>
                            <p class="purple-title" style="text-decoration:underline; margin: unset; align-self:center;">Modify</p>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <br /><br /><br />
    <div class="col-lg-10 d-flex">
            <div class="col-lg-6 d-flex justify-content-start pl-0">
                <button type="button" class="btn btn-danger btn-lg" v-on:click="onCancel()"
                        style="border-radius:18px; max-width: 190px; width:100%;">
                    <div class="d-flex justify-content-center" style="max-height: 20px;">
                        <p style="margin:unset;">Don't save </p>
                    </div>
                </button> @*TODO: Replace this with static text*@
            </div>
        <div class="col-lg-6 d-flex justify-content-center pr-0">
            <div class="col-lg-12 d-flex justify-content-end pr-0">
                <button type="button" class="btn btn-success btn-lg" v-on:click="submitResults()"
                        style="border-radius:18px; max-width: 190px; width:100%;">
                    <div class="d-flex justify-content-between" style="max-height: 20px;">
                        <p style="margin:unset;">Validate </p>
                        <i style="margin-top: 2px;" class="fa fa-arrow-right"></i>
                    </div>
                </button> @*TODO: Replace this with static text*@
            </div>
        </div>
    </div>
</div>

@section Scripts{

    
    @Html.Partial("../Components/ExpParticipantResult/SingleExperimentResultCmp.cshtml")

<script type="text/javascript">
    var experimentIdGlobal = @ViewBag.experimentId;
    var participantIdGlobal = "@ViewBag.participantId";
    var experimentWizardSamplePickerPage = "@Url.Action("ExperimentWizardResume", "Experiment")"
    var experimentListPage = "@Url.Action("List","Experiment")";
</script>


<script src="~/js/Models/Experiment.js" asp-append-version="true"></script>
<script src="~/js/ExperimentWizardSteps/ExperimentWizardResume.js" asp-append-version="true"></script>

}

TrailAir.Web.UI/Views/Experiment/ExperimentWizardSteps/ExperimentWizardSamplePicker.cshtml
<div class="row wrapper purple-2-bg page-heading" style="min-height:90vh;">
    <br />
    <div class="col-lg-12 d-flex justify-content-center">
        <h2 class="purple-title">
            @*TODO: Replace this with static text*@
            Please select a sample
        </h2>
    </div>
    <div style="width:100%;">
        <div class="col-lg-8 d-flex justify-content-start" style="flex-basis: 33.333333%; flex-wrap: wrap; margin: auto;">
            <div class="col-lg-4 cursor-pointer" style="margin-top: 40px;"
                 v-for="(x, index) in currentElement.bechTestSampleResults" :disabled="x.isSubmitted">
                <div class="d-flex flex-column align-items-center justify-content-center"
                     style="height:150px; border-radius:45px;" :class="{ 'grey-back' : x.isSubmitted, 'purple-1-bg purple-hover' : !x.isSubmitted }"
                     v-on:click="openExperimentWizardTest(x, x.expResultType)">
                    <img src="~/images/CalibrateLogo-WhiteTransparentBack.PNG" class="mb-2" />
                    <h3 class="text-light mb-3">Insert:</h3> @*TODO: Replace this with static text*@
                    <h3 class="text-light">Sample {{x.sampleCode}}</h3> @*TODO: Replace this with static text*@
                </div>
            </div>
        </div>
    </div>

    <div style="width: 100%; height: fit-content; align-self: end; margin-top: 15px;">
        <div class="col-lg-8 d-flex" style="margin: auto;">
            <div class="col-lg-6">
                <div class="col-lg-6 d-flex justify-content-start pl-0">
                    <button type="button" class="btn btn-danger btn-lg" v-on:click="dontSave()"
                            style="border-radius:18px; max-width: 190px; width:100%;">
                        <div class="d-flex justify-content-center" style="max-height: 20px;">
                            <p style="margin:unset;">Don't save </p>
                        </div>
                    </button> @*TODO: Replace this with static text*@
                </div>
            </div>
            <div class="col-lg-6 d-flex justify-content-end mr-0">
                <button type="button" :disabled="isResumeButtonDisabled" class="btn btn-success btn-lg" v-on:click="goToResumePage()"
                        style="border-radius:18px; max-width: 190px; width:100%;">
                    <div class="d-flex justify-content-between" style="max-height: 20px;">
                        <p style="margin:unset;">Resume and validate</p>
                        <i style="margin-top: 2px;" class="fa fa-arrow-right"></i>
                    </div>
                </button> @*TODO: Replace this with static text*@
            </div>
        </div>
    </div>
</div>

@section Scripts{

<script type="text/javascript">
    var experimentIdGlobal = @ViewBag.experimentId;
    var participantIdGlobal = "@ViewBag.participantId";
    var experimentListPage = "@Url.Action("List","Experiment")";
    var experimentWizardTestPage = "@Url.Action("ExperimentWizardTest", "Experiment")"
    var experimentWizardResumePage = "@Url.Action("ExperimentWizardResume", "Experiment")" /*TODO:Remove this after you're done!!*/
</script>

<script src="~/js/Models/Experiment.js" asp-append-version="true"></script>
<script src="~/js/ExperimentWizardSteps/ExperimentWizardSamplePicker.js" asp-append-version="true"></script>
}